#!/usr/bin/env python3
"""Keep the single-file installer in sync with the files it embeds.

``scripts/setup/install.sh`` is published as one file (the curl one-liner has no
sibling files), so it carries copies of:

* the release public key (``pkg/keys/meshloom.asc``), its pinned fingerprint
  (``pkg/keys/FINGERPRINT``) and the SHA-256 of the dearmored keyring;
* the compose update helper and its systemd units (``scripts/setup/helpers``);
* the apt pin shipped by the package (``pkg/nfpm/meshloom.pref``).

Run without arguments after changing any of them; ``--check`` exits 1 when the
installer is stale (tests and CI use it).
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INSTALL_SH = ROOT / "scripts" / "setup" / "install.sh"
KEYS = ROOT / "pkg" / "keys"

HEREDOC_EMBEDS = {
    "scripts/setup/helpers/compose-update": "_embed_compose_update",
    "scripts/setup/helpers/meshloom-compose-update.service.in": "_embed_compose_service",
    "scripts/setup/helpers/meshloom-compose-update.path.in": "_embed_compose_path",
    "pkg/nfpm/meshloom.pref": "_embed_apt_pin",
}
EOF_MARK = "MESHLOOM_EMBED_EOF"
FPR_RE = re.compile(r"^[0-9A-F]{40}$")


def dearmor(text: str) -> bytes | None:
    """Binary packets of an ASCII-armored public key block, or None."""
    lines = text.replace("\r", "").split("\n")
    try:
        start = lines.index("-----BEGIN PGP PUBLIC KEY BLOCK-----")
        end = lines.index("-----END PGP PUBLIC KEY BLOCK-----", start)
    except ValueError:
        return None
    body = lines[start + 1 : end]
    if "" not in body:
        return None
    body = body[body.index("") + 1 :]
    payload = "".join(line for line in body if line and not line.startswith("="))
    try:
        data = base64.b64decode(payload, validate=True)
    except ValueError:
        return None
    return data or None


def key_block() -> str:
    asc_path = KEYS / "meshloom.asc"
    fpr_path = KEYS / "FINGERPRINT"
    asc = asc_path.read_text(encoding="utf-8") if asc_path.exists() else ""
    fpr = fpr_path.read_text(encoding="utf-8").strip() if fpr_path.exists() else ""
    packets = dearmor(asc)
    if packets is None or not FPR_RE.match(fpr):
        # Placeholder keys: the installer refuses package and compose installs.
        asc, fpr, digest = "", "", ""
    else:
        asc = asc.replace("\r", "").strip() + "\n"
        digest = hashlib.sha256(packets).hexdigest()
    if "'" in asc:
        raise SystemExit("unexpected quote in meshloom.asc")
    return (
        f"MESHLOOM_KEY_FINGERPRINT='{fpr}'\n"
        f"MESHLOOM_KEYRING_SHA256='{digest}'\n"
        f"MESHLOOM_KEY_ASC='{asc}'\n"
    )


def heredoc_block(rel: str, func: str) -> str:
    text = (ROOT / rel).read_text(encoding="utf-8")
    if not text.endswith("\n"):
        text += "\n"
    if f"\n{EOF_MARK}\n" in f"\n{text}":
        raise SystemExit(f"{rel} contains the heredoc terminator")
    return f"{func}() {{\n    cat <<'{EOF_MARK}'\n{text}{EOF_MARK}\n}}\n"


def blocks() -> dict[str, str]:
    out = {"pkg/keys": key_block()}
    for rel, func in HEREDOC_EMBEDS.items():
        out[rel] = heredoc_block(rel, func)
    return out


def render(text: str) -> str:
    for name, body in blocks().items():
        begin = f"# >>> embed: {name} (generated by scripts/setup/sync_installer_embeds.py; do not edit)\n"
        end = f"# <<< embed: {name}\n"
        pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
        if not pattern.search(text):
            raise SystemExit(f"install.sh has no embed markers for {name}")
        text = pattern.sub(lambda _m, b=begin, body=body, e=end: b + body + e, text, count=1)
    return text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if install.sh is stale")
    args = parser.parse_args(argv)
    current = INSTALL_SH.read_text(encoding="utf-8")
    wanted = render(current)
    if args.check:
        if current != wanted:
            print("scripts/setup/install.sh is stale: run scripts/setup/sync_installer_embeds.py")
            return 1
        return 0
    if current != wanted:
        INSTALL_SH.write_text(wanted, encoding="utf-8")
        print("updated scripts/setup/install.sh")
    return 0


if __name__ == "__main__":
    sys.exit(main())
