/**
 * Keyword index for composer emoji search. Keys are the Open reaction glyphs;
 * values are space-separated English and French terms (plus a few aliases).
 */

const EMOJI_KEYWORDS: Record<string, string> = {
  '👍': 'thumbs up like yes pouce haut ok',
  '❤️': 'heart love red coeur cœur rouge',
  '😂': 'joy tears laugh lol rire pleure',
  '🎉': 'party popper tada fete fête',
  '👏': 'clap applause bravo applaudir',
  '🔥': 'fire hot feu flamme',
  '😀': 'grinning smile happy sourire content',
  '😃': 'smile big eyes happy sourire',
  '😄': 'smile eyes happy sourire',
  '😁': 'beaming grin sourire dents',
  '😅': 'sweat smile awkward ouf',
  '🤣': 'rofl rolling laugh mort de rire',
  '😊': 'blush smile happy sourire',
  '😇': 'angel halo innocent ange',
  '🙂': 'slight smile sourire',
  '🙃': 'upside down inverse',
  '😉': 'wink clin oeil œil',
  '😌': 'relieved calm ouf soulage',
  '😍': 'heart eyes love amour',
  '🥰': 'smiling hearts love amour',
  '😘': 'kiss bisou',
  '😗': 'kiss bisou',
  '😙': 'kiss smile bisou',
  '😚': 'kiss closed eyes bisou',
  '😋': 'yum tasty savoureux',
  '😛': 'tongue langue',
  '😝': 'tongue squint langue',
  '😜': 'wink tongue langue',
  '🤪': 'zany crazy fou',
  '🤨': 'raised eyebrow doute',
  '🧐': 'monocle inspect',
  '🤓': 'nerd lunettes',
  '😎': 'cool sunglasses lunettes',
  '🥸': 'disguise deguise déguisé',
  '🤩': 'star struck wow etoile étoile',
  '🥳': 'partying birthday fete fête',
  '😏': 'smirk sourire narquois',
  '😒': 'unamused ennuye',
  '😞': 'disappointed deçu',
  '😔': 'pensive pensif',
  '😟': 'worried inquiet',
  '😕': 'confused confus',
  '🙁': 'frown triste',
  '😣': 'persevering peine',
  '😖': 'confounded contrarie',
  '😫': 'tired fatigue fatigué',
  '😩': 'weary las',
  '🥺': 'pleading please s il te plait',
  '😢': 'cry sad pleure triste',
  '😭': 'sob cry pleure',
  '😤': 'steam angry rage',
  '😠': 'angry colere colère',
  '😡': 'pouting rage colere colère',
  '🤬': 'swearing insulte',
  '🤯': 'exploding head choc',
  '😳': 'flushed gene gêné',
  '🥵': 'hot hotface chaud',
  '🥶': 'cold freezing froid',
  '😱': 'scream fear peur',
  '😨': 'fearful peur',
  '😰': 'anxious sweat peur',
  '😥': 'sad relieved ouf',
  '😓': 'downcast sweat sueur',
  '🤗': 'hug calin câlin',
  '🤔': 'thinking pense',
  '🤭': 'hand over mouth oops',
  '🤫': 'shush quiet chut',
  '🤥': 'lying pinocchio mensonge',
  '😶': 'no mouth silence',
  '👎': 'thumbs down dislike pouce bas',
  '👊': 'fist bump poing',
  '✊': 'raised fist poing',
  '🤛': 'left fist poing',
  '🤜': 'right fist poing',
  '🤞': 'crossed fingers chance',
  '✌️': 'victory peace victoire paix',
  '🤟': 'love you iloveyou',
  '🤘': 'horns rock metal',
  '👌': 'ok okay parfait',
  '🤌': 'pinched fingers italien',
  '🤏': 'pinching petit',
  '👈': 'left pointer gauche',
  '👉': 'right pointer droite',
  '👆': 'up pointer haut',
  '👇': 'down pointer bas',
  '☝️': 'index up index',
  '👋': 'wave hello salut',
  '🤚': 'raised back hand main',
  '🖐️': 'hand fingers main',
  '✋': 'raised hand stop main',
  '🖖': 'vulcan spock',
  '🙌': 'raising hands hooray bravo',
  '👐': 'open hands mains',
  '🤲': 'palms up priere',
  '🤝': 'handshake deal accord',
  '🙏': 'pray please merci priere prière',
  '✍️': 'writing ecrire écrire',
  '💅': 'nail polish vernis',
  '🤳': 'selfie',
  '💪': 'muscle strong biceps force',
  '🧡': 'orange heart coeur cœur',
  '💛': 'yellow heart coeur cœur',
  '💚': 'green heart coeur cœur',
  '💙': 'blue heart coeur cœur',
  '💜': 'purple heart coeur cœur',
  '🖤': 'black heart coeur cœur noir',
  '🤍': 'white heart coeur cœur blanc',
  '🤎': 'brown heart coeur cœur',
  '💔': 'broken heart coeur brise cœur brisé',
  '❤️‍🔥': 'heart on fire passion feu',
  '❤️‍🩹': 'mending heart guerison',
  '💕': 'two hearts amour',
  '💞': 'revolving hearts amour',
  '💓': 'beating heart battement',
  '💗': 'growing heart amour',
  '💖': 'sparkling heart amour',
  '💘': 'heart arrow cupidon',
  '💝': 'heart ribbon cadeau',
  '💟': 'heart decoration',
  '💌': 'love letter lettre',
  '💢': 'anger vein colere',
  '💥': 'collision boom explosion',
  '💫': 'dizzy etoile étoile',
  '💦': 'sweat drops sueur',
  '💨': 'dash wind vent',
  '🕳️': 'hole trou',
  '💬': 'speech bubble parole',
  '👁️‍🗨️': 'eye speech',
  '🗨️': 'left speech',
  '🗯️': 'anger bubble',
  '💭': 'thought pensee pensée',
  '🎊': 'confetti ball',
  '🎈': 'balloon ballon',
  '🎁': 'gift present cadeau',
  '🎀': 'ribbon noeud nœud',
  '🪅': 'pinata piñata',
  '🪆': 'nesting dolls matriochka',
  '🏆': 'trophy trophee trophée',
  '🥇': 'gold medal or',
  '🥈': 'silver medal argent',
  '🥉': 'bronze medal bronze',
  '⚽': 'soccer football',
  '⚾': 'baseball',
  '🥎': 'softball',
  '🏀': 'basketball basket',
  '🏐': 'volleyball volley',
  '🏈': 'football american',
  '🏉': 'rugby',
  '🎾': 'tennis',
  '🥏': 'flying disc frisbee',
  '🎳': 'bowling',
  '🏏': 'cricket',
  '🏑': 'field hockey',
  '🏒': 'ice hockey',
  '🥍': 'lacrosse',
  '🏓': 'ping pong tennis table',
  '🏸': 'badminton',
  '🥊': 'boxing glove boxe',
  '🥋': 'martial arts judo',
  '🥅': 'goal net but',
  '⛳': 'flag in hole golf',
  '⭐': 'star etoile étoile',
  '🌟': 'glowing star etoile étoile',
  '✨': 'sparkles etincelles étincelles',
  '⚡': 'zap lightning eclair éclair',
  '💡': 'bulb idea idee idée',
  '🔦': 'flashlight lampe',
  '🏮': 'red lantern lanterne',
  '🪔': 'diya lamp',
  '📱': 'phone mobile telephone téléphone',
  '💻': 'laptop computer ordinateur',
  '⌚': 'watch montre',
  '📷': 'camera photo',
  '📺': 'tv television télévision',
  '📻': 'radio',
  '🎵': 'musical note musique',
  '🎶': 'musical notes musique',
  '🚀': 'rocket fusee fusée',
};

function normalizeQuery(query: string): string {
  return query.trim().toLowerCase().normalize('NFD').replace(/\p{M}/gu, '');
}

function uniqueInOrder(emojis: readonly string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const emoji of emojis) {
    if (seen.has(emoji)) continue;
    seen.add(emoji);
    out.push(emoji);
  }
  return out;
}

/** Filter a composer emoji list by character or keyword. Empty query keeps order. */
export function filterEmojis(emojis: readonly string[], query: string): string[] {
  const unique = uniqueInOrder(emojis);
  const needle = normalizeQuery(query);
  if (!needle) return unique;
  return unique.filter((emoji) => {
    if (emoji.includes(query.trim())) return true;
    const keywords = EMOJI_KEYWORDS[emoji] ?? '';
    return normalizeQuery(`${emoji} ${keywords}`).includes(needle);
  });
}
